name: barber
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  flutter_modular: ^5.0.3
  dart_ping: ^8.0.1
  dart_ping_ios: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flextras: ^1.0.0
  flutter_animate: ^4.1.1+1
  flutter_native_splash: ^2.3.1
  flutter_vibrate: ^1.3.0
  gap: ^3.0.0
  intl: ^0.18.0
  bot_toast: ^4.0.4
  flutter_bloc: ^8.1.3
  loading_animation_widget: ^1.2.0+4
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  streaming_shared_preferences: ^2.0.0
  path_provider: ^2.0.15
  path_provider_foundation: ^2.2.3
  easy_mask: ^2.0.1
  flux_validator_dart: ^2.0.0
  flutter_svg: ^2.0.7
  url_strategy: ^0.2.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
