// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Epu1wDBNdTVtWksd-hRILKsqUM4m6p0',
    appId: '1:559368787575:web:9079796e2e18eadab61872',
    messagingSenderId: '559368787575',
    projectId: 'barber-d47a8',
    authDomain: 'barber-d47a8.firebaseapp.com',
    storageBucket: 'barber-d47a8.appspot.com',
    measurementId: 'G-EJJC3BP60E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnCJlhAeoC091wF8MFsmaVW8Jq1iCAixg',
    appId: '1:559368787575:android:1925829a996025f2b61872',
    messagingSenderId: '559368787575',
    projectId: 'barber-d47a8',
    storageBucket: 'barber-d47a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyzN05B4MK-dK9pd_Xoe0ywFvkadskYM',
    appId: '1:559368787575:ios:56eb88a5e2ded69fb61872',
    messagingSenderId: '559368787575',
    projectId: 'barber-d47a8',
    storageBucket: 'barber-d47a8.appspot.com',
    iosClientId: '559368787575-6bvu04kt6qdu2dpqb7c4rkm9q1973h9o.apps.googleusercontent.com',
    iosBundleId: 'br.com.zety.barber',
  );
}
